<a href="https://colab.research.google.com/github/suryasai99/Practice/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import numpy as np

In [2]:
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [3]:
print(x.shape)

torch.Size([1, 2])


In [4]:
print(y.shape)

torch.Size([2, 1])


In [5]:
print(x.dtype)

torch.int64


In [6]:
# creating 0's of 4 rows 5 cols
a = torch.zeros((4,5))
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
# creating 1's of 4 rows 5 cols
b = torch.ones((4,5))
print(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [8]:
c = torch.zeros_like(a)

In [9]:
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
# Distribution intergers
print(torch.randint(3, 10, (2,3)))

tensor([[4, 8, 3],
        [6, 4, 9]])


In [11]:
# normal distribution
print(torch.randn(3,8))

tensor([[ 0.4344,  0.9850,  0.0761,  0.7420,  0.7112, -0.0471, -0.8552,  0.5973],
        [-0.7013, -0.0975, -0.4393,  2.3856, -0.1324, -0.1292,  0.6529, -1.5935],
        [ 0.6773, -0.5806,  0.7752, -0.0771, -0.5024, -0.0863, -1.4943, -0.3749]])


In [12]:
# random distribution
print(torch.rand(4,6))

tensor([[0.6591, 0.2519, 0.0725, 0.3941, 0.3172, 0.4207],
        [0.3807, 0.6997, 0.1020, 0.2786, 0.4780, 0.1442],
        [0.0377, 0.8368, 0.5773, 0.2667, 0.5830, 0.2225],
        [0.3468, 0.4129, 0.8876, 0.7355, 0.1184, 0.5912]])


In [14]:
x = np.array([[10,20,30],[2,3,4]])

In [15]:
print(x.dtype)

int64


In [16]:
# converting numpy array to tensor
x = torch.tensor(x)
print(x.dtype)

torch.int64


In [17]:
type(x)

torch.Tensor

In [18]:
# multiplication
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(torch.mul(x, 10))

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [19]:
print(torch.add(x, 23))

tensor([[24, 25, 26, 27],
        [28, 29, 30, 31]])


In [20]:
# reshaping
z = x.view(4,2)

In [21]:
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [24]:
# reshaping with squeeze
x = torch.randn([10, 1, 10])

In [25]:
print(x)

tensor([[[ 0.5432, -0.0854,  0.8598,  0.7362, -0.4962,  0.9657, -1.2636,
           0.8091,  0.6096, -1.7309]],

        [[ 0.1291, -0.2967, -0.1560, -0.0390, -0.4368,  1.0636, -0.7506,
           0.6771, -0.5356, -0.4474]],

        [[-0.2601, -0.7182, -0.7730, -1.9722, -0.1591, -0.7222,  0.5082,
          -1.4638,  0.8465,  0.1748]],

        [[ 0.0749, -1.1919, -0.2836, -1.0161, -0.4517, -0.2662,  1.1089,
          -1.4799, -0.0697, -0.5959]],

        [[-0.4967,  0.2676,  0.9955, -0.3993,  1.0421, -1.0404, -0.9334,
           0.4723,  0.3924, -1.1253]],

        [[ 0.0400,  1.3952, -0.0321, -0.6934,  0.6346,  0.7668,  2.8163,
           0.0952,  1.1859, -1.8688]],

        [[-1.0434, -1.2370, -0.5500, -2.0450, -0.0575, -0.3212, -1.8281,
          -1.1255,  0.1998, -0.1118]],

        [[ 0.3963,  0.6211,  1.1482, -1.5473,  0.4803,  1.4941,  0.8982,
          -0.7191,  1.0985, -1.1542]],

        [[ 0.4306,  1.5789,  0.4447,  0.0693,  1.4543, -0.3988, -1.2600,
          -1.9274, -1.4

In [26]:
# squeezing the index 1
z1 = x.squeeze(1)

In [27]:
print(z1)

tensor([[ 0.5432, -0.0854,  0.8598,  0.7362, -0.4962,  0.9657, -1.2636,  0.8091,
          0.6096, -1.7309],
        [ 0.1291, -0.2967, -0.1560, -0.0390, -0.4368,  1.0636, -0.7506,  0.6771,
         -0.5356, -0.4474],
        [-0.2601, -0.7182, -0.7730, -1.9722, -0.1591, -0.7222,  0.5082, -1.4638,
          0.8465,  0.1748],
        [ 0.0749, -1.1919, -0.2836, -1.0161, -0.4517, -0.2662,  1.1089, -1.4799,
         -0.0697, -0.5959],
        [-0.4967,  0.2676,  0.9955, -0.3993,  1.0421, -1.0404, -0.9334,  0.4723,
          0.3924, -1.1253],
        [ 0.0400,  1.3952, -0.0321, -0.6934,  0.6346,  0.7668,  2.8163,  0.0952,
          1.1859, -1.8688],
        [-1.0434, -1.2370, -0.5500, -2.0450, -0.0575, -0.3212, -1.8281, -1.1255,
          0.1998, -0.1118],
        [ 0.3963,  0.6211,  1.1482, -1.5473,  0.4803,  1.4941,  0.8982, -0.7191,
          1.0985, -1.1542],
        [ 0.4306,  1.5789,  0.4447,  0.0693,  1.4543, -0.3988, -1.2600, -1.9274,
         -1.4934,  0.4675],
        [ 0.7655, -

In [28]:
z2 = z1.unsqueeze(1)

In [29]:
print(z2)

tensor([[[ 0.5432, -0.0854,  0.8598,  0.7362, -0.4962,  0.9657, -1.2636,
           0.8091,  0.6096, -1.7309]],

        [[ 0.1291, -0.2967, -0.1560, -0.0390, -0.4368,  1.0636, -0.7506,
           0.6771, -0.5356, -0.4474]],

        [[-0.2601, -0.7182, -0.7730, -1.9722, -0.1591, -0.7222,  0.5082,
          -1.4638,  0.8465,  0.1748]],

        [[ 0.0749, -1.1919, -0.2836, -1.0161, -0.4517, -0.2662,  1.1089,
          -1.4799, -0.0697, -0.5959]],

        [[-0.4967,  0.2676,  0.9955, -0.3993,  1.0421, -1.0404, -0.9334,
           0.4723,  0.3924, -1.1253]],

        [[ 0.0400,  1.3952, -0.0321, -0.6934,  0.6346,  0.7668,  2.8163,
           0.0952,  1.1859, -1.8688]],

        [[-1.0434, -1.2370, -0.5500, -2.0450, -0.0575, -0.3212, -1.8281,
          -1.1255,  0.1998, -0.1118]],

        [[ 0.3963,  0.6211,  1.1482, -1.5473,  0.4803,  1.4941,  0.8982,
          -0.7191,  1.0985, -1.1542]],

        [[ 0.4306,  1.5789,  0.4447,  0.0693,  1.4543, -0.3988, -1.2600,
          -1.9274, -1.4

In [37]:
y = torch.randn(1, 10, 10)

In [40]:
z = y.squeeze(0)

In [41]:
print(z)

tensor([[ 1.0027,  0.4809,  0.1841,  2.2992, -1.0313, -1.1074,  0.3182, -0.0125,
          1.0830, -0.0843],
        [ 0.1614,  0.0337,  0.8717,  0.3383,  1.2991,  0.0027,  0.7156, -0.5091,
         -0.3490, -1.5758],
        [-1.4616, -1.3318, -0.7695, -1.4043, -0.7584,  1.2558,  0.7800, -0.5468,
         -0.7096,  1.8405],
        [ 0.1693, -0.2191, -0.4956, -2.0690,  0.3983, -0.9510,  0.8530,  0.4090,
          0.1555, -0.6425],
        [-0.4409,  0.1633,  0.3361, -0.0750, -0.8280,  0.6710, -1.7730,  0.4982,
         -0.0310, -2.0329],
        [ 0.1529, -0.0995, -0.2288, -0.4637, -1.8820,  0.0386,  0.4465,  1.1961,
          0.8259, -0.4011],
        [ 0.6441, -0.1824,  0.1439,  0.5395,  0.9342, -0.3517,  0.1412,  0.7535,
         -0.8287,  1.4116],
        [ 0.8559, -1.1383, -0.3301,  1.0710,  0.2169, -0.3676, -0.1037, -0.1169,
          1.2419,  0.5459],
        [-1.4366, -0.1714, -1.5136, -0.3984, -0.4292, -1.0099,  2.4486, -1.8846,
         -0.6245, -2.2842],
        [-1.3473, -

In [46]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = x.mul(21).view(4,2)

In [47]:
print(y)

tensor([[ 21,  42],
        [ 63,  84],
        [105, 126],
        [147, 168]])


In [48]:
# MATRIX multiplication
print(x@y)

tensor([[1050, 1260],
        [2394, 2940]])


In [49]:
# MATRIX multiplication
print(torch.matmul(x, y))

tensor([[1050, 1260],
        [2394, 2940]])


In [56]:
x = torch.randn(10, 10)

In [57]:
print(x)

tensor([[ 1.9397,  1.0565,  0.5590, -0.0698,  0.2741, -1.5930, -0.4697, -0.9720,
         -0.3755, -1.0077],
        [-0.0384, -0.5068, -0.2999,  0.6542,  1.0952,  1.3424,  1.2073, -1.0818,
         -0.2221,  0.2412],
        [ 0.3567, -0.6441, -0.2829, -1.7887,  0.9260,  0.1496, -1.6396, -0.4145,
          0.2115,  0.2643],
        [-0.9068, -0.4128, -0.2750, -0.4973, -0.4923,  0.3191,  0.2259, -1.1008,
         -0.6864,  1.0643],
        [ 0.5291,  1.1756, -1.7324,  0.4802, -0.2076, -0.7420, -1.5430, -0.2456,
          0.5593, -1.1289],
        [ 0.1918,  1.1982,  0.2186,  0.2124, -0.5821,  0.4591, -1.1691,  0.5944,
         -1.1760, -2.1368],
        [ 1.1072,  0.8290, -0.7297, -1.6144, -0.4057,  1.1015,  0.0257,  0.3784,
         -0.7421, -1.2667],
        [-1.1502, -1.7554, -0.4857, -0.2450,  0.3977, -0.3952, -0.1557, -1.1320,
          1.5997,  0.6832],
        [ 0.0641,  0.9293, -1.7799,  1.2104,  1.9661,  0.2742, -0.6813, -1.3574,
         -0.5134,  1.0816],
        [-0.0912, -

In [58]:
print(torch.cat([x, x], axis = 0))

tensor([[ 1.9397,  1.0565,  0.5590, -0.0698,  0.2741, -1.5930, -0.4697, -0.9720,
         -0.3755, -1.0077],
        [-0.0384, -0.5068, -0.2999,  0.6542,  1.0952,  1.3424,  1.2073, -1.0818,
         -0.2221,  0.2412],
        [ 0.3567, -0.6441, -0.2829, -1.7887,  0.9260,  0.1496, -1.6396, -0.4145,
          0.2115,  0.2643],
        [-0.9068, -0.4128, -0.2750, -0.4973, -0.4923,  0.3191,  0.2259, -1.1008,
         -0.6864,  1.0643],
        [ 0.5291,  1.1756, -1.7324,  0.4802, -0.2076, -0.7420, -1.5430, -0.2456,
          0.5593, -1.1289],
        [ 0.1918,  1.1982,  0.2186,  0.2124, -0.5821,  0.4591, -1.1691,  0.5944,
         -1.1760, -2.1368],
        [ 1.1072,  0.8290, -0.7297, -1.6144, -0.4057,  1.1015,  0.0257,  0.3784,
         -0.7421, -1.2667],
        [-1.1502, -1.7554, -0.4857, -0.2450,  0.3977, -0.3952, -0.1557, -1.1320,
          1.5997,  0.6832],
        [ 0.0641,  0.9293, -1.7799,  1.2104,  1.9661,  0.2742, -0.6813, -1.3574,
         -0.5134,  1.0816],
        [-0.0912, -

In [59]:
print(torch.cat([x, x], axis = 1))

tensor([[ 1.9397,  1.0565,  0.5590, -0.0698,  0.2741, -1.5930, -0.4697, -0.9720,
         -0.3755, -1.0077,  1.9397,  1.0565,  0.5590, -0.0698,  0.2741, -1.5930,
         -0.4697, -0.9720, -0.3755, -1.0077],
        [-0.0384, -0.5068, -0.2999,  0.6542,  1.0952,  1.3424,  1.2073, -1.0818,
         -0.2221,  0.2412, -0.0384, -0.5068, -0.2999,  0.6542,  1.0952,  1.3424,
          1.2073, -1.0818, -0.2221,  0.2412],
        [ 0.3567, -0.6441, -0.2829, -1.7887,  0.9260,  0.1496, -1.6396, -0.4145,
          0.2115,  0.2643,  0.3567, -0.6441, -0.2829, -1.7887,  0.9260,  0.1496,
         -1.6396, -0.4145,  0.2115,  0.2643],
        [-0.9068, -0.4128, -0.2750, -0.4973, -0.4923,  0.3191,  0.2259, -1.1008,
         -0.6864,  1.0643, -0.9068, -0.4128, -0.2750, -0.4973, -0.4923,  0.3191,
          0.2259, -1.1008, -0.6864,  1.0643],
        [ 0.5291,  1.1756, -1.7324,  0.4802, -0.2076, -0.7420, -1.5430, -0.2456,
          0.5593, -1.1289,  0.5291,  1.1756, -1.7324,  0.4802, -0.2076, -0.7420,
      

In [60]:
x = torch.arange(25).reshape(5,5)

In [61]:
print(x)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


In [62]:
print(x.max())

tensor(24)


In [63]:
m,argm = torch.max(x, dim = 0)

In [64]:
print(m, argm)

tensor([20, 21, 22, 23, 24]) tensor([4, 4, 4, 4, 4])


In [65]:
m1, argm1 = torch.max(x, dim = 1)
print(m1, argm1)

tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


In [67]:
y = torch.randint(0, 25, (5,5))
print(y)

tensor([[10,  1, 21, 15, 11],
        [ 8, 17, 20, 11, 13],
        [10, 14,  3, 19, 10],
        [18, 19, 18,  5, 18],
        [23, 16, 21, 14, 16]])


In [68]:
m,argm = torch.max(y, dim = 0)

In [69]:
print(m, argm)

tensor([23, 19, 21, 19, 18]) tensor([4, 3, 0, 2, 3])


In [70]:
m1, argm1 = torch.max(y, dim = 1)
print(m1, argm1)

tensor([21, 20, 19, 19, 23]) tensor([2, 2, 3, 1, 0])


In [71]:
c = torch.randn(3, 4, 5)
print(c)

tensor([[[-0.6195,  1.2516, -2.3465,  0.0376,  0.1281],
         [-1.3530, -1.1817, -0.3447,  0.5848, -0.3103],
         [-0.4200,  0.1483, -1.0098, -0.1522, -1.3749],
         [-0.1537, -0.8335, -0.7925, -0.3071,  1.4506]],

        [[-0.2412, -0.6333, -0.1910,  0.3199, -0.6481],
         [-0.1013, -0.6549, -1.8346, -0.0453,  0.6268],
         [ 0.0094, -0.4573,  1.0322,  0.0830, -0.8362],
         [-0.8501,  1.2055, -1.0730,  1.2205, -0.8246]],

        [[ 1.8574,  0.6068,  0.5146,  1.7549, -0.4967],
         [ 0.3319, -0.7117, -0.5716,  0.0448, -0.1048],
         [ 1.7363, -0.9159,  0.3654, -1.2744, -0.3833],
         [-0.5555, -0.7620, -0.4246, -1.2801, -0.0260]]])


In [72]:
# reshaping using permute
print(c.permute(2, 0, 1))

tensor([[[-0.6195, -1.3530, -0.4200, -0.1537],
         [-0.2412, -0.1013,  0.0094, -0.8501],
         [ 1.8574,  0.3319,  1.7363, -0.5555]],

        [[ 1.2516, -1.1817,  0.1483, -0.8335],
         [-0.6333, -0.6549, -0.4573,  1.2055],
         [ 0.6068, -0.7117, -0.9159, -0.7620]],

        [[-2.3465, -0.3447, -1.0098, -0.7925],
         [-0.1910, -1.8346,  1.0322, -1.0730],
         [ 0.5146, -0.5716,  0.3654, -0.4246]],

        [[ 0.0376,  0.5848, -0.1522, -0.3071],
         [ 0.3199, -0.0453,  0.0830,  1.2205],
         [ 1.7549,  0.0448, -1.2744, -1.2801]],

        [[ 0.1281, -0.3103, -1.3749,  1.4506],
         [-0.6481,  0.6268, -0.8362, -0.8246],
         [-0.4967, -0.1048, -0.3833, -0.0260]]])
